name: Terraform CI (OIDC)

on:
  pull_request:
  push:
    branches: ["**"]

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    env:
      TF_IN_AUTOMATION: true
      TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
      TF_BACKEND_KEY: ${{ secrets.TF_BACKEND_KEY }}
      TF_BACKEND_REGION: ${{ secrets.TF_BACKEND_REGION }}
      TF_BACKEND_DDB_TABLE: ${{ secrets.TF_BACKEND_DDB_TABLE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::579989519757:role/GitHubTerraformRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init (remote backend via secrets)
        run: |
          terraform init             -backend-config="bucket=${ '{' } env.TF_BACKEND_BUCKET { '}' }"             -backend-config="key=${ '{' } env.TF_BACKEND_KEY { '}' }"             -backend-config="region=${ '{' } env.TF_BACKEND_REGION { '}' }"             -backend-config="dynamodb_table=${ '{' } env.TF_BACKEND_DDB_TABLE { '}' }"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -out=tfplan
